# Generated by Django 4.1.1 on 2022-09-10 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('ID_ESPECIALIDAD', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('ID_FAMILIAR', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('ID_MEDICO', models.AutoField(primary_key=True, serialize=False)),
                ('Registro', models.CharField(max_length=60)),
                ('ID_ESPECIALIDAD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('ID_PACIENTE', models.AutoField(primary_key=True, serialize=False)),
                ('Direccion', models.CharField(max_length=255)),
                ('Ciudad', models.CharField(max_length=60)),
                ('Latitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('Longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Familiar_ID_FAMILIAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.familiar')),
                ('Medico_ID_MEDICO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ID_PERSONA', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60)),
                ('Apellido', models.CharField(max_length=60)),
                ('Telefono', models.CharField(max_length=60)),
                ('Genero', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('ID_ROL', models.AutoField(primary_key=True, serialize=False)),
                ('Rol', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Signos_vitales',
            fields=[
                ('ID_SIGNO_VITAL', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_Signo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='T_Diagnostico',
            fields=[
                ('ID_DIAGNOSTICO', models.BigAutoField(primary_key=True, serialize=False)),
                ('Diagnostico', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('ID_MEDICO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.medico')),
                ('ID_PACIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID_LOGIN', models.AutoField(primary_key=True, serialize=False)),
                ('Contraseña', models.CharField(max_length=60)),
                ('ID_ROL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.rol')),
            ],
        ),
        migrations.CreateModel(
            name='T_Sugerencias',
            fields=[
                ('ID_SUGERENCIAS', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('ID_DIAGNOSTICO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.t_diagnostico')),
                ('ID_MEDICO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_SV',
            fields=[
                ('ID_REGISTRO_SV', models.AutoField(primary_key=True, serialize=False)),
                ('Medida', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Fecha_Hora', models.DateTimeField()),
                ('Fecha_Nacimiento', models.CharField(max_length=128)),
                ('Paciente_ID_PACIENTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.medico')),
                ('SV_ID_SIGNO_VITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='Identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.usuarios'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Persona_ID_PERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.persona'),
        ),
        migrations.AddField(
            model_name='medico',
            name='ID_PERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.persona'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='ID_PERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.persona'),
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('ID_ENFERMERO', models.AutoField(primary_key=True, serialize=False)),
                ('ID_PERSONA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('ID_AUXILIAR', models.AutoField(primary_key=True, serialize=False)),
                ('ID_PERSONA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.persona')),
            ],
        ),
    ]
