# Generated by Django 4.1.1 on 2022-09-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='Contraseña',
            new_name='Password',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Familiar_ID_FAMILIAR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.familiar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Medico_ID_MEDICO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.medico'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ID_LOGIN',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
