# Generated by Django 4.1.1 on 2022-09-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0002_rename_contraseña_usuarios_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='ID_ESPECIALIDAD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.especialidad'),
        ),
    ]
