# Generated by Django 4.1.1 on 2022-09-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0004_alter_registro_sv_paciente_id_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_sv',
            name='Fecha_Nacimiento',
        ),
    ]
