# Generated by Django 4.1.1 on 2022-09-15 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0005_remove_registro_sv_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_sv',
            name='SV_ID_SIGNO_VITAL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeCareApp.signos_vitales'),
        ),
    ]
