# Generated by Django 4.1.1 on 2022-09-16 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0006_alter_registro_sv_sv_id_signo_vital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_sv',
            name='Fecha_Hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
