# Generated by Django 4.1.1 on 2022-09-16 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0008_alter_registro_sv_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_sv',
            name='Fecha_Hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
