# Generated by Django 4.1.1 on 2022-09-17 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0009_alter_registro_sv_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_diagnostico',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='t_sugerencias',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
