CREATE TABLE Medico (
	ID_MEDICO INT NOT NULL AUTO_INCREMENT,
    ID_PERSONA INT NOT NULL,
    Especialidad VARCHAR(60) NOT NULL,
    Registro VARCHAR(60) NOT NULL,
    PRIMARY KEY (ID_MEDICO)
    -- FOREIGN KEY (ID_PERSONA) REFERENCES Persona(ID_PERSONA) -- 
    );
    
    
CREATE TABLE T_Sugerencias (
	ID_SUGERENCIAS INT NOT NULL AUTO_INCREMENT,
    ID_MEDICO INT NOT NULL,
    ID_DIAGNOSTICO BIGINT NOT NULL,
    fecha_hora DATETIME NOT NULL,
    descripcion TEXT NOT NULL,
    PRIMARY KEY(ID_SUGERENCIAS),
    FOREIGN KEY(ID_MEDICO) REFERENCES Medico(ID_MEDICO),
    FOREIGN KEY(ID_DIAGNOSTICO) REFERENCES T_Diagnostico(ID_DIAGNOSTICO)
);

CREATE TABLE T_Diagnostico (
	ID_DIAGNOSTICO BIGINT NOT NULL AUTO_INCREMENT,
    ID_PACIENTE INT NOT NULL,
    ID_MEDICO INT NOT NULL,
    Diagnostico TEXT NOT NULL,
    fecha_hora DATETIME NOT NULL,
    PRIMARY KEY(ID_DIAGNOSTICO),
    -- FOREIGN KEY(ID_PACIENTE) REFERENCES Paciente(ID_PACIENTE), --
    FOREIGN KEY (ID_MEDICO) REFERENCES Medico(ID_MEDICO)    
);