CREATE SCHEMA BD_HOME_CARE;
USE BD_HOME_CARE;

CREATE TABLE Paciente (
    ID_PACIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    Persona_ID_PERSONA INT NOT NULL,
    Medico_ID_MEDICO INT NOT NULL,
    Familiar_ID_FAMILIAR INT NOT NULL,
    Direccion CHAR(255) NOT NULL,
    Ciudad CHAR(60) INT NOT NULL,
    Latitud DECIMAL(6,5) INT NOT NULL,
    Longitud DECIMAL(6,5) INT NOT NULL,
    Fecha_Nacimiento DATE NOT NULL,
    FOREIGN KEY (Persona_ID_PERSONA) REFERENCES Persona(ID_PERSONA),     
    FOREIGN KEY (Medico_ID_MEDICO) REFERENCES Medico(ID_MEDICO),
    FOREIGN KEY (Familiar_ID_FAMILIAR) REFERENCES Familiar(ID_FAMILIAR)
);
   

CREATE TABLE Signos_vitales(
    ID_SIGNO_VITAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    Tipo_Signo CHAR(60) INT NOT NULL
    );

CREATE TABLE Registro_SV(
    ID_REGISTRO_SV BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    SV_ID_SIGNO_VITAL INT NOT NULL,
    Paciente_ID_PACIENTE INT NOT NULL,
    Medida DECIMAL(6,3) NOT NULL,
    Fecha_Hora DATETIME NOT NULL,
    FOREIGN KEY (SV_ID_SIGNO_VITAL) REFERENCES Signos_vitales(ID_SIGNO_VITAL),
    FOREIGN KEY (Paciente_ID_PACIENTE) REFERENCES Paciente(ID_PACIENTE)
    );