CREATE SCHEMA BD_HOME_CARE;
USE BD_HOME_CARE;

CREATE TABLE Persona{
    ID_PERSONA INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
    Identificacion VARCHAR(60) NOT NULL,
    Apellido  VARCHAR(60) NOT NULL,
    Telefono VARCHAR(60) NOT NULL,
    Genero VARCHAR(60) NOT NULL,
    Email VARCHAR(60) NOT NULL
    -- ID_ROL INT NOT NULL,
    -- FOREIGN KEY ID_ROL REFERENCES Rol(ID_ROL)
};

CREATE TABLE Auxiliar{
    ID_AUXILIAR INT PRIMARY KEY NOT NULL
    ID_PERSONA INT NOT NULL
    FOREIGN KEY ID_PERSONA REFERENCES persona(ID_PERSONA)
};

CREATE TABLE Familiar{
    ID_FAMILIAR INT PRIMARY AUTO_INCREMENT KEY NOT NULL,
    parentesco VARCHAR(60) NOT NULL
    ID_PERSONA INT NOT NULL
    FOREIGN KEY ID_PERSONA REFERENCES persona(ID_PERSONA)
};

CREATE TABLE Enfermero{
    ID_ENFERMERO INT PRIMARY AUTO_INCREMENT KEY NOT NULL
    ID_PERSONA INT NOT NULL
    FOREIGN KEY ID_PERSONA REFERENCES persona(ID_PERSONA)
};